FROM python:3.13-bookworm

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y git

RUN git clone https://github.com/kernelci/kcidb.git && \
    cd kcidb && \
    pip install -e .

COPY ingester_poc.py /app/ingester_poc.py

CMD ["python", "/app/ingester_poc.py", "--spool-dir", "/app/spool"]

