# Dockerfile for kcidb-rest-rs

FROM rust:bookworm

# update to latest rust
RUN rustup update

WORKDIR /app

RUN mkdir -p spool

COPY kcidb-restd-rs/ .

RUN cargo build --release

# secondary image slim bookworm
FROM debian:bookworm-slim

COPY --from=0 /app/target/release/kcidb-restd-rs /usr/local/bin/kcidb-restd-rs
COPY --from=0 /app/static/index.html /usr/local/share/kcidb-restd-rs/index.html

CMD ["kcidb-restd-rs"]


