FROM python:3.13-bookworm

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y git

RUN git clone https://github.com/kernelci/kcidb.git && \
    cd kcidb && \
    pip install -e .

COPY ingester/ingester.py /app/ingester.py
COPY data/trees.yml /app/trees.yml

CMD ["python", "/app/ingester.py", "--spool-dir", "/app/spool"]

