#!/bin/bash
echo "Initializing database..."
psql -h db -U postgres -c "CREATE ROLE kcidb WITH LOGIN PASSWORD 'kcidb';"
psql -h db -U postgres -c "CREATE DATABASE kcidb WITH OWNER kcidb;"
psql -h db -U postgres -c "CREATE ROLE kcidb_editor WITH LOGIN PASSWORD 'kcidb';"
psql -h db -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE kcidb TO kcidb_editor;"
psql -h db -U postgres -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO kcidb_editor;"
psql -h db -U postgres -c "GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO kcidb_editor;"
psql -h db -U postgres -c "GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO kcidb_editor;"
# add kcidb_editor who can write
psql -h db -U postgres -c "ALTER ROLE kcidb_editor SET client_encoding TO 'utf8';"
psql -h db -U postgres -c "ALTER ROLE kcidb_editor SET default_transaction_isolation TO 'read committed';"
psql -h db -U postgres -c "ALTER ROLE kcidb_editor SET timezone TO 'UTC';"
# add kcidb_viewer who can read only
psql -h db -U postgres -c "CREATE ROLE kcidb_viewer WITH LOGIN PASSWORD 'kcidb';"
psql -h db -U postgres -c "GRANT CONNECT ON DATABASE kcidb TO kcidb_viewer;"
psql -h db -U postgres -c "GRANT USAGE ON SCHEMA public TO kcidb_viewer;"
psql -h db -U postgres -c "GRANT SELECT ON ALL TABLES IN SCHEMA public TO kcidb_viewer;"
psql -h db -U postgres -c "GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO kcidb_viewer;"
psql -h db -U postgres -c "ALTER ROLE kcidb_viewer SET client_encoding TO 'utf8';"
psql -h db -U postgres -c "ALTER ROLE kcidb_viewer SET default_transaction_isolation TO 'read committed';"
psql -h db -U postgres -c "ALTER ROLE kcidb_viewer SET timezone TO 'UTC';"
echo "Database initialized."
echo "Creating DB schema for kcidb..."
kcidb-db-init -d "${PG_URI}" --ignore-initialized
echo "DB schema created."
